version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: custom-lidarr_server_1
      APP_PORT: 8686
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - '/home/server/drive:/home/server/drive:rw'
    restart: on-failure

  mac:
    image: getumbrel/media-app-configurator:v1.0.0@sha256:e3d8b18e0186f76dd3f3d4acacc9101b4abbf302d8f2afbb47cdd3879b1a1008
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - '/home/server/drive:/home/server/drive:rw'
    environment:
      DOWNLOAD_CLIENT_API_URL: "http://custom-lidarr_server_1:8686/api/v1/downloadclient"
      ROOT_FOLDER_API_URL: "http://custom-lidarr_server_1:8686/api/v1/rootfolder"
      TRANSMISSION_HOST: "custom-transmission-openvpn_server_1"
      TRANSMISSION_PORT: 9091
      ROOT_FOLDER: "/home/server/drive/music"
