version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: transmission-openvpn
      APP_PORT: 9091

  server:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - OPENVPN_PROVIDER=Ihr_OpenVPN_Provider
      - OPENVPN_CONFIG=Ihr_OpenVPN_Config
      - OPENVPN_USERNAME=Ihr_OpenVPN_Benutzername
      - OPENVPN_PASSWORD=Ihr_OpenVPN_Passwort
      - LOCAL_NETWORK=Ihr_Lokales_Netzwerk
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=Ihr_Transmission_Benutzername
      - TRANSMISSION_RPC_PASSWORD=Ihr_Transmission_Passwort
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    restart: on-failure
